### ISSUE TITLE
autocompletion or check the existence for an audio file

### ISSUE THREAD

**Issue by carpanera** [boyska/larigira#34]
larigira doesn't know if a file really exist. So if someone type the wrong name or path filling the form the action will be valid, but de facto broken.

**Comment by boyska** [comment]
Ok. This requires adding a configuration option that is a list of "base file path". This option will have an effect only on WebUI.

Every (with probably some maximum) file (with valid extension, non-zero size, etc) will be added to a datalist of valid files. That will provide autocompletion.

Entering a value that is not part of the datalist should give you a warning (but no problems entering it)

**Comment by boyska** [comment]
In commit af9464 , autocompletion has been implemented for most forms. There is still no warning for invalid input

**Comment by boyska** [comment]
Done (a70033e)
